version: '3.7'

services:
    api-graphql:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
    
    db:
        image: postgres:13.2-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=recipe_db

volumes:
    postgres_data: